In [37]:
import numpy as np
import sympy as sym
from IPython.display import display,Math
sym.init_printing()
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from google.colab import data_table
import pandas as pd

#1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [2]:
# scaler
tf.constant(np.random.rand(1))

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.5239449])>

In [3]:
# vector
tf.constant(np.random.randint(1,10,(10)))

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([6, 2, 5, 9, 4, 5, 2, 7, 6, 6])>

In [4]:
# matrix
tf.constant(np.random.randint(1,9,(3,3)))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[7, 2, 7],
       [8, 8, 7],
       [6, 3, 1]])>

In [5]:
# tensor

tensor = tf.constant(np.random.randint(1,99,(2,3,5)))
tensor

<tf.Tensor: shape=(2, 3, 5), dtype=int64, numpy=
array([[[89, 16, 82, 81, 94],
        [44, 32, 92, 66, 44],
        [70, 90, 36,  4, 96]],

       [[60, 66, 22, 87, 57],
        [41, 92, 69,  4, 97],
        [64, 89, 95,  3, 45]]])>

# 2.Find the shape, rank and size of the tensors you created in 1.



In [6]:
tensor.shape

TensorShape([2, 3, 5])

In [7]:
tf.rank(tensor).numpy()

3

In [8]:
tf.size(tensor).numpy() # counts the number of elements in the tensor

30

# 3.Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [9]:
a = tf.constant(np.random.rand(5,300))
b = tf.constant(np.random.rand(5,300))

# 4. Multiply the two tensors you created in 3 using matrix multiplication.


In [10]:
tf.matmul(a,np.transpose(b))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[79.86956932, 70.32395032, 73.78358294, 72.37650018, 71.3232028 ],
       [75.65534956, 69.42512717, 64.97930478, 65.16766717, 67.17935197],
       [77.54807428, 68.28973371, 70.79872947, 71.76051432, 69.34574023],
       [85.95508962, 78.39082242, 75.2212089 , 75.00573007, 75.56504453],
       [80.55620692, 70.39878121, 72.87211952, 71.57405027, 70.62859557]])>

# 5. Multiply the two tensors you created in 3 using dot product

In [11]:
tf.tensordot(a,np.transpose(b),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[79.86956932, 70.32395032, 73.78358294, 72.37650018, 71.3232028 ],
       [75.65534956, 69.42512717, 64.97930478, 65.16766717, 67.17935197],
       [77.54807428, 68.28973371, 70.79872947, 71.76051432, 69.34574023],
       [85.95508962, 78.39082242, 75.2212089 , 75.00573007, 75.56504453],
       [80.55620692, 70.39878121, 72.87211952, 71.57405027, 70.62859557]])>

# 6.Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [12]:
a = tf.constant(np.random.rand(224,224,3))
a

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.92179934, 0.45386664, 0.05802304],
        [0.51930169, 0.16499801, 0.38962857],
        [0.95939025, 0.92160051, 0.80392205],
        ...,
        [0.11901739, 0.69494691, 0.79542433],
        [0.33832008, 0.44351881, 0.11056991],
        [0.55260663, 0.29522427, 0.4599005 ]],

       [[0.99224134, 0.95772414, 0.06428442],
        [0.28794754, 0.68137479, 0.16586508],
        [0.67263674, 0.42748121, 0.08660948],
        ...,
        [0.89576056, 0.93852906, 0.23988619],
        [0.54956958, 0.96953011, 0.62337199],
        [0.77966235, 0.09059058, 0.62461344]],

       [[0.3948171 , 0.6002772 , 0.86319911],
        [0.70589498, 0.41722388, 0.04079446],
        [0.28884248, 0.41794742, 0.36521166],
        ...,
        [0.18157139, 0.5914412 , 0.24313597],
        [0.89825448, 0.44307549, 0.16917688],
        [0.96293548, 0.61642239, 0.96776242]],

       ...,

       [[0.3473866 , 0.60286249, 0.51695433],
        [0.59

# 7.Find the min and max values of the tensor you created in 6 along the first axis.

In [13]:
tf.math.reduce_max(a,axis=1)

<tf.Tensor: shape=(224, 3), dtype=float64, numpy=
array([[0.99318316, 0.99854381, 0.99587963],
       [0.99575554, 0.99422587, 0.9918321 ],
       [0.99762348, 0.99384792, 0.99865526],
       [0.9975654 , 0.98790755, 0.99344388],
       [0.99899471, 0.99901904, 0.96336481],
       [0.99599169, 0.98376672, 0.99921604],
       [0.99845917, 0.99841573, 0.98624132],
       [0.99362437, 0.99271633, 0.99658316],
       [0.9949464 , 0.99540452, 0.99538899],
       [0.99632562, 0.99985854, 0.99656541],
       [0.998468  , 0.99202746, 0.9920722 ],
       [0.99526976, 0.98756008, 0.98023968],
       [0.99872057, 0.99814099, 0.99448943],
       [0.99496948, 0.99043651, 0.99958768],
       [0.99974566, 0.99482742, 0.99489781],
       [0.99931454, 0.99994532, 0.98919761],
       [0.99787904, 0.99834997, 0.99856248],
       [0.99789776, 0.9971192 , 0.99267183],
       [0.9953896 , 0.99856399, 0.9975361 ],
       [0.99249283, 0.99064941, 0.99471151],
       [0.99505291, 0.99873446, 0.99145673],
     

In [14]:
tf.math.reduce_min(a,axis=1)

<tf.Tensor: shape=(224, 3), dtype=float64, numpy=
array([[8.97381411e-03, 3.72889590e-03, 1.59892606e-04],
       [1.25089648e-03, 1.91179180e-02, 1.34113084e-04],
       [4.91270814e-03, 1.02554016e-02, 1.68089247e-03],
       [8.34059237e-03, 2.97472030e-03, 9.50716299e-04],
       [1.35248220e-02, 2.33608567e-03, 8.74343435e-04],
       [1.59941524e-03, 4.55226581e-03, 3.27840320e-04],
       [2.17725195e-03, 1.08789841e-03, 3.28047193e-03],
       [1.93896943e-03, 2.53415275e-03, 2.50331385e-03],
       [1.35985800e-03, 5.86554695e-03, 5.03067380e-03],
       [8.83916643e-03, 1.01593949e-02, 5.28475272e-03],
       [1.17063698e-03, 4.17409532e-03, 4.47116474e-03],
       [3.47147130e-03, 1.05798753e-04, 3.31305751e-03],
       [1.41079246e-03, 5.86413635e-03, 2.09131108e-03],
       [9.40798185e-04, 2.95241861e-02, 1.53428535e-03],
       [6.01381699e-03, 8.63602751e-03, 5.27403467e-03],
       [1.76713687e-03, 4.84009705e-04, 1.49049422e-03],
       [6.68565777e-03, 6.55301887e-04

In [15]:
tf.math.reduce_min(a)

<tf.Tensor: shape=(), dtype=float64, numpy=1.1366196839279752e-07>

In [16]:
tf.math.reduce_max(a)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9999701512941469>

# 8.Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [17]:
a = tf.constant(np.random.randint(1,9,(1,224,224,3)))

a.shape

TensorShape([1, 224, 224, 3])

In [18]:
tf.squeeze(a).shape

TensorShape([224, 224, 3])

# 9.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [19]:
a = tf.constant(np.random.randn(10))
a

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([-0.65649795,  1.07244002, -0.06539927,  1.09673253,  0.92992665,
       -2.52432896,  2.1481551 , -0.86158539, -0.12167731, -0.67145888])>

In [20]:
max_index = tf.argmax(a).numpy()

max_index

6

In [21]:
a[max_index]

<tf.Tensor: shape=(), dtype=float64, numpy=2.148155095658114>

# 10. One-hot encode a tensor containing a bunch of colors .

In [22]:
color_string = ['red','green','blue','yellow','pink','red','blue','red','lime','red','red','lime','red','blue']

dic = {color:index for index,color in enumerate(color_string)}

numbers_one_hot_code = [dic[color] for color in color_string]

tf.one_hot(numbers_one_hot_code,depth=len(color_string))

<tf.Tensor: shape=(14, 14), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
      dtype=float32)>

In [23]:
dic

{'red': 12, 'green': 1, 'blue': 13, 'yellow': 3, 'pink': 4, 'lime': 11}

In [24]:
numbers_one_hot_code

[12, 1, 13, 3, 4, 12, 13, 12, 11, 12, 12, 11, 12, 13]

# Eigen values

In [30]:
a = tf.constant(np.random.randint(1,99,(2,3,5)),dtype=tf.float16)
a

<tf.Tensor: shape=(2, 3, 5), dtype=float16, numpy=
array([[[ 1.,  6., 82., 80., 96.],
        [13.,  2., 80., 23.,  1.],
        [53., 93., 53., 43.,  1.]],

       [[69., 78., 78., 92., 29.],
        [46., 46., 18., 16., 22.],
        [37., 18., 81., 42., 83.]]], dtype=float16)>

In [26]:
help(tf.eig)

Help on function eig in module tensorflow.python.ops.linalg_ops:

eig(tensor, name=None)
    Computes the eigen decomposition of a batch of matrices.
    
    The eigenvalues
    and eigenvectors for a non-Hermitian matrix in general are complex. The
    eigenvectors are not guaranteed to be linearly independent.
    
    Computes the eigenvalues and right eigenvectors of the innermost
    N-by-N matrices in `tensor` such that
    `tensor[...,:,:] * v[..., :,i] = e[..., i] * v[...,:,i]`, for i=0...N-1.
    
    Args:
      tensor: `Tensor` of shape `[..., N, N]`. Only the lower triangular part of
        each inner inner matrix is referenced.
      name: string, optional name of the operation.
    
    Returns:
      e: Eigenvalues. Shape is `[..., N]`. The eigenvalues are not necessarily
         ordered.
      v: Eigenvectors. Shape is `[..., N, N]`. The columns of the inner most
        matrices contain eigenvectors of the corresponding matrices in `tensor`



In [31]:
eigen_values,eigen_vectors = tf.linalg.eig(a)

UnboundLocalError: ignored

### eigen values can be found only if the tensor is a square tensor and dtype should be float32

In [28]:
a = tf.constant(np.random.randint(1,99,(3,3,3)),dtype=tf.float32)
tf.eig(a)

(<tf.Tensor: shape=(3, 3), dtype=complex64, numpy=
 array([[168.31863  +0.j      , -35.68948  +0.j      ,
          35.370853 +0.j      ],
        [128.60118  +0.j      ,  18.199415+18.837404j,
          18.199415-18.837404j],
        [174.89227  +0.j      ,  35.476955 +0.j      ,
         -46.369167 +0.j      ]], dtype=complex64)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=complex64, numpy=
 array([[[-0.68185467+0.j        , -0.82791126+0.j        ,
           0.10889405+0.j        ],
         [-0.2717922 +0.j        ,  0.32096276+0.j        ,
          -0.7975127 +0.j        ],
         [-0.67911947+0.j        ,  0.45994112+0.j        ,
           0.59339315+0.j        ]],
 
        [[-0.58297485+0.j        , -0.10338615+0.31678322j,
          -0.10338615-0.31678322j],
         [-0.5523266 +0.j        , -0.4093376 -0.00853446j,
          -0.4093376 +0.00853446j],
         [-0.5958822 +0.j        ,  0.75342435-0.39202213j,
           0.75342435+0.39202213j]],
 
        [[ 0.46224156+0.j    

# day 119

# grocery bill tensor

In [36]:
grocery_bill = [
    ['Beans', 'Sugar', 'Honey', 'Hide & seek biscuit', 'vitamin tablets', 'rava'],
    [5, 3, 1, 8, 1, 0.25],
    [142, 50, 534, 40, 5000, 64]
]

grocery_bill

[['Beans', 'Sugar', 'Honey', 'Hide & seek biscuit', 'vitamin tablets', 'rava'],
 [5, 3, 1, 8, 1, 0.25],
 [142, 50, 534, 40, 5000, 64]]

In [38]:
columns = ['Name','Qty','Price']

In [40]:
pd.DataFrame(grocery_bill,index=columns)

0      1      2                    3                4     5
Name   Beans  Sugar  Honey  Hide & seek biscuit  vitamin tablets  rava
Qty        5      3      1                    8                1  0.25
Price    142     50    534                   40             5000    64

In [55]:
grocery_bill = tf.constant([[5,3,1,8,1,0.25],[152,50,534,40,5000,64]])

grocery_bill

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[5.00e+00, 3.00e+00, 1.00e+00, 8.00e+00, 1.00e+00, 2.50e-01],
       [1.52e+02, 5.00e+01, 5.34e+02, 4.00e+01, 5.00e+03, 6.40e+01]],
      dtype=float32)>

In [56]:
grocery_bill.shape

TensorShape([2, 6])

In [57]:
grocery_bill = tf.transpose(grocery_bill)
grocery_bill

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[5.00e+00, 1.52e+02],
       [3.00e+00, 5.00e+01],
       [1.00e+00, 5.34e+02],
       [8.00e+00, 4.00e+01],
       [1.00e+00, 5.00e+03],
       [2.50e-01, 6.40e+01]], dtype=float32)>

In [58]:
qty = grocery_bill[:,0]
qty

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([5.  , 3.  , 1.  , 8.  , 1.  , 0.25], dtype=float32)>

In [59]:
price = grocery_bill[:,1]
price

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 152.,   50.,  534.,   40., 5000.,   64.], dtype=float32)>

In [64]:
total_amount_paid = tf.cast(price*qty,dtype=tf.float32)
tf.math.reduce_sum(total_amount_paid).numpy()

6780.0