# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

# day 113 and day 114

In [50]:
# Import NumPy as its abbreviation 'np'
import numpy as np
import pandas as pd
import sympy as sym
from IPython.display import display,Math
sym.init_printing()

In [2]:
# Create a 1-dimensional NumPy array using np.array()
one_dim = np.arange(1,9,2)

# Create a 2-dimensional NumPy array using np.array()
two_dim = np.random.randint(1,9,(3,3))

# Create a 3-dimensional Numpy array using np.array()
three_dim = np.array([np.random.randint(1,9,(3,3))])

In [4]:
one_dim

array([1, 3, 5, 7])

In [5]:
two_dim

array([[8, 6, 8],
       [4, 7, 3],
       [8, 3, 5]])

In [6]:
three_dim

array([[[7, 3, 7],
        [3, 1, 1],
        [5, 4, 1]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
np.shape(one_dim), one_dim.ndim, type(one_dim)

((4,), 1, numpy.ndarray)

In [9]:
# Attributes of 2-dimensional array
np.shape(two_dim), two_dim.ndim, type(two_dim)

((3, 3), 2, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
np.shape(three_dim), three_dim.ndim, type(three_dim)

((1, 3, 3), 3, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

dic = {'1D':one_dim}
pd.DataFrame(data=dic)

1D
0   1
1   3
2   5
3   7

In [7]:
pd.DataFrame(data=two_dim)

0  1  2
0  8  8  3
1  6  3  7
2  4  5  6

In [12]:
three_dim

array([[[8, 4, 2],
        [7, 1, 8],
        [3, 8, 3]]])

In [25]:
# converting three_dim to 2d

data = three_dim.reshape(-1,three_dim.shape[2])
pd.DataFrame(data)

0  1  2
0  8  4  2
1  7  1  8
2  3  8  3

In [26]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
np.ones((3,4,1))

array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])

In [30]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [31]:
np.ones((3,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [36]:
np.ones(shape=(3,4,3,2,2))

array([[[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]],



       [[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.]

In [27]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros(shape=(7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,101,3) # 100 inclusive.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [37]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,(7,2))

array([[9, 5],
       [6, 9],
       [5, 9],
       [7, 6],
       [5, 8],
       [0, 0],
       [7, 0]])

In [39]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3,5)

array([[0.27723305, 0.55015629, 0.5132824 , 0.91101903, 0.13518118],
       [0.28625802, 0.47622265, 0.10151679, 0.49582632, 0.94028264],
       [0.64580161, 0.86064087, 0.83167899, 0.71429957, 0.12081748]])

In [42]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [43]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

x = np.random.randint(1,10,(3,7))
# Find the unique numbers in the array you just created
np.unique(x)

array([1, 2, 3, 4, 5, 7, 9])

In [48]:
x

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [45]:
# Find the 0'th index of the latest array you created
x[0]

array([9, 1, 3, 7, 4, 9, 3])

In [47]:
# Get the first 2 rows of latest array you created
x[:2,:]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [49]:
# Get the first 2 values of the first 2 rows of the latest array
x[:2,:2]

array([[9, 1],
       [5, 3]])

In [56]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
x = np.random.randint(0,10,(3,5))
ones = np.ones(shape=(3,5))

display(Math(sym.latex(sym.sympify(x))))
print(' ')
display(Math(sym.latex(sym.sympify(ones))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [57]:
# Add the two arrays together
x + ones

array([[ 7.,  1.,  4.,  4.,  5.],
       [ 7.,  7.,  4.,  7.,  3.],
       [ 6.,  2., 10.,  9.,  5.]])

In [58]:
# Create another array of ones of shape (5, 3)

another_ones = np.ones(shape=(5,3))

another_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
# Try add the array of ones and the other most recent array together
x + another_ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [65]:
np.dot(x,another_ones)

# this is how we fix it.

array([[16., 16., 16.],
       [23., 23., 23.],
       [27., 27., 27.]])

In [60]:
# Create another array of ones of shape (3, 5)

ones = np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
# Subtract the new array of ones from the other most recent array
x - ones

array([[ 5., -1.,  2.,  2.,  3.],
       [ 5.,  5.,  2.,  5.,  1.],
       [ 4.,  0.,  8.,  7.,  3.]])

In [62]:
# Multiply the ones array with the latest array
x * ones

array([[6., 0., 3., 3., 4.],
       [6., 6., 3., 6., 2.],
       [5., 1., 9., 8., 4.]])

In [63]:
# Take the latest array to the power of 2 using '**'
x ** 2

array([[36,  0,  9,  9, 16],
       [36, 36,  9, 36,  4],
       [25,  1, 81, 64, 16]], dtype=int32)

In [64]:
# Do the same thing with np.square()
np.square(x)

array([[36,  0,  9,  9, 16],
       [36, 36,  9, 36,  4],
       [25,  1, 81, 64, 16]], dtype=int32)

In [66]:
# Find the mean of the latest array using np.mean()
np.mean(x)

In [67]:
# Find the maximum of the latest array using np.max()
np.max(x)

9

In [68]:
# Find the minimum of the latest array using np.min()
np.min(x)

0

In [69]:
# Find the standard deviation of the latest array
np.std(x)

In [70]:
# Find the variance of the latest array
np.var(x)

In [71]:
x

array([[6, 0, 3, 3, 4],
       [6, 6, 3, 6, 2],
       [5, 1, 9, 8, 4]])

In [73]:
# Reshape the latest array to (3, 5, 1)
x.reshape((3,5,1))

array([[[6],
        [0],
        [3],
        [3],
        [4]],

       [[6],
        [6],
        [3],
        [6],
        [2]],

       [[5],
        [1],
        [9],
        [8],
        [4]]])

In [74]:
# Transpose the latest array
np.transpose(x)

array([[6, 6, 5],
       [0, 6, 1],
       [3, 3, 9],
       [3, 6, 8],
       [4, 2, 4]])

What does the transpose do?

In [75]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
x = np.random.randint(0,10,(3,3))
y = np.random.randint(0,10,(3,2))



In [76]:
# Perform a dot product on the two newest arrays you created
np.dot(x,y)

array([[118,  66],
       [148,  64],
       [ 48,  40]])

In [77]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
x = np.random.randint(0,10,(4,3))
y = np.random.randint(0,10,(4,3))

In [78]:
# Perform a dot product on the two newest arrays you created
np.dot(x,y)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [79]:
# fixing it 
np.dot(x,y.T) # taking a transpose of y(3,4)

array([[84, 58, 32, 49],
       [45, 20,  8,  0],
       [66, 61, 20, 49],
       [27, 51, 12, 56]])

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
# did it already?

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [80]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
x = np.random.randint(0,10,(4,3))
y = np.random.randint(0,10,(4,3))



In [82]:
x

array([[1, 1, 5],
       [6, 4, 0],
       [0, 2, 1],
       [4, 9, 5]])

In [83]:
y

array([[6, 3, 6],
       [7, 0, 5],
       [7, 4, 3],
       [1, 5, 5]])

In [81]:
# Compare the two arrays with '>'
x > y


array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [84]:
# Compare the two arrays with '>='
x >= y

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [ True,  True,  True]])

In [85]:
# Find which elements of the first array are greater than 7
x > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [86]:
# Which parts of each array are equal? (try using '==')
x == y

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [88]:
x

array([[1, 1, 5],
       [6, 4, 0],
       [0, 2, 1],
       [4, 9, 5]])

In [87]:
# Sort one of the arrays you just created in ascending order
np.sort(x)

array([[1, 1, 5],
       [0, 4, 6],
       [0, 1, 2],
       [4, 5, 9]])

In [89]:
# show the indexes of one of the arrays you just created
np.argsort(x)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1],
       [0, 2, 1]], dtype=int64)

In [90]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(x)

10

In [91]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(x)

5

In [93]:
x

array([[1, 1, 5],
       [6, 4, 0],
       [0, 2, 1],
       [4, 9, 5]])

In [94]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(x,axis=1)

array([2, 0, 1, 1], dtype=int64)

In [95]:
np.argmax(x,axis=0)

array([1, 3, 0], dtype=int64)

In [96]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(x,axis=0)

array([2, 0, 1], dtype=int64)

In [97]:
# Create an array of normally distributed random numbers
np.random.randn(10)

array([-0.88064082,  0.07689495, -0.49343248,  0.92316261,  1.70660495,
        0.87358942,  0.00914435, -0.3655393 ,  0.64908673, -1.22287354])

In [98]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.