# Numpy:



# seaborn, matplotlib, pandas,scikit learn are all built off of numpy
# numpy is fundamental
# numpy has the built in tools for statistical analysis (data analysis), trignometric functions, linear algebra.


In [2]:
# numpy arrays:
import numpy as np

lis=[1,2,3,4]

arr=np.array(lis)
arr

array([1, 2, 3, 4])

In [12]:
# the list l still remains as same (unaffected)

lis

[1, 2, 3, 4]

In [18]:
#creating matrix like structure from normal python nested lists

lis1=[[1,2,3],[4,5,6],[7,8,9]]
print("lis1 is : {}".format(lis1))

#now see the magic

matrix1=np.matrix(lis1)
matrix1

lis1 is : [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
# using print format

print(" matrix is :{}".format(matrix1))

#now looks disheveled. really disheveled!

 matrix is :[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import os
print(os.getcwd())


C:\Users\ADMIN\for machine learning\Basic Python


In [4]:
#this numpy function gives a range of number with specified step size.
# note it is 'arange'_meaning something like 'a range', not 'arrange'_arranging in order.

np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [5]:
#gives five ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
#gives five zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
#gives zeros in 2 rows and 5 columns full
#note double parenthesis
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
#just like in r language we have some unique function in python that outputs evenly spaced numbers between a range of numbers 

np.linspace(0,11,89)

array([ 0.   ,  0.125,  0.25 ,  0.375,  0.5  ,  0.625,  0.75 ,  0.875,
        1.   ,  1.125,  1.25 ,  1.375,  1.5  ,  1.625,  1.75 ,  1.875,
        2.   ,  2.125,  2.25 ,  2.375,  2.5  ,  2.625,  2.75 ,  2.875,
        3.   ,  3.125,  3.25 ,  3.375,  3.5  ,  3.625,  3.75 ,  3.875,
        4.   ,  4.125,  4.25 ,  4.375,  4.5  ,  4.625,  4.75 ,  4.875,
        5.   ,  5.125,  5.25 ,  5.375,  5.5  ,  5.625,  5.75 ,  5.875,
        6.   ,  6.125,  6.25 ,  6.375,  6.5  ,  6.625,  6.75 ,  6.875,
        7.   ,  7.125,  7.25 ,  7.375,  7.5  ,  7.625,  7.75 ,  7.875,
        8.   ,  8.125,  8.25 ,  8.375,  8.5  ,  8.625,  8.75 ,  8.875,
        9.   ,  9.125,  9.25 ,  9.375,  9.5  ,  9.625,  9.75 ,  9.875,
       10.   , 10.125, 10.25 , 10.375, 10.5  , 10.625, 10.75 , 10.875,
       11.   ])

In [16]:
#linspace means linearly spaced or evenly spaced in common language

#gives out 4 evenly spaced numbers between o and 30

np.linspace(0,30,4)

array([ 0., 10., 20., 30.])

In [15]:
#gives 20 linearly spaced numbers between 0 and 100
#for readability either increase the start number by 1 or step number by 1 np.linspace(0,100,21 not 20) to get desired outcome

np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

# list reshaping into matrix

In [21]:
lis=[range(1,10)]

#we get a bunch of numbers in lis which is converted to matrix and reshaped to 3*3 format
matrix=np.matrix(lis).reshape(3,3) 
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# random functions in numpy.random

In [24]:
#gives a bunch of random numbers picked between 0 and 1
np.random.rand()

0.8016534198741382

In [25]:
#gives an array of five random numbers in the range between 0 and 1
np.random.rand(5)

array([0.79807854, 0.14312623, 0.53976657, 0.7959373 , 0.66983152])

In [26]:
#gives a matrix of random numbers between 0 and 1
np.random.rand(3,3)

array([[0.33170971, 0.13736056, 0.82201403],
       [0.55258848, 0.86992899, 0.41932444],
       [0.95642159, 0.03882508, 0.4051126 ]])

In [28]:
# random.randn() means normal distribution random with the mean of 0 and a standard deviation of 1
#it can give any random value however,99.7% of the times its value will fall between -3 and +3 (3 stds)

np.random.randn()

-1.383779871769104

In [29]:
#a matrix of randn numbers 
np.random.randn(3,5)

array([[ 1.73426781, -1.36876858,  0.2199177 ,  1.9641973 ,  1.36912779],
       [ 0.67237917,  0.29457913,  0.11188659, -0.76152978, -0.94898333],
       [-1.75041843,  0.0843747 ,  1.30928771,  0.66492093,  0.04080258]])

In [39]:
#rand int

#between 10 and 101 get a number
np.random.randint(10,101)

89

In [40]:
#between 10 and 101 get 10 numbers
np.random.randint(10,101,10)

array([10, 20, 54, 46, 73, 51, 18, 87, 80, 91])

In [41]:
#between 10 and 101 get 9 numbers in 3*3 matrix
np.random.randint(10,101,(3,3))

array([[65, 39, 22],
       [87, 90, 98],
       [57, 90, 67]])

# numpy.random.seed()

In [4]:
#numpy.random.seed(number of choice ) helps to produce the same random results over and over.
np.random.seed(4)
a=np.random.randint(0,10,15)
a

array([7, 5, 1, 8, 7, 8, 2, 9, 7, 7, 7, 9, 8, 4, 2])

In [50]:
#random.seed() makes the 'random' array be the same throughout the workbook
a

array([7, 5, 1, 8, 7, 8, 2, 9, 7, 7, 7, 9, 8, 4, 2])

In [51]:
#min value from the array 'a' can be fetched using min() function
a.min()

1

In [52]:
#max value of the array 'a' can be fetched using max() function
a.max()

9

In [53]:
# argmax() gives the first index position of the maximum value

a.argmax()

7

In [54]:
# argmin() gives the first index position of the minimum value

a.argmin()

2

In [55]:
# to find out the precision at which your computer does the calculation 32 or 64 bit

a.dtype

dtype('int32')

In [57]:
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

# array indexing and selecting

In [59]:
#note it is a range not arrange

arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
#we are changing all the numbers from index 0th till 5th but not including 5th index into 7

arr[0:5]=7
arr

array([ 7,  7,  7,  7,  7,  5,  6,  7,  8,  9, 10])

In [62]:
# array copy 

#we take a copy of the original array that way any change we brought on about the arr2 is not linked back and reflected in arr

arr2=arr.copy()

In [63]:
arr2

array([ 7,  7,  7,  7,  7,  5,  6,  7,  8,  9, 10])

In [66]:
#this is not going to be a part of numpy if we do not use numpy functions 
#so this way of 
lis=[[1,2,3],[4,5,6],[7,8,9]]

arr2d=np.matrix(lis)
arr2d

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
# #note '.'and without 'bracket' is attribute 
# '.' and 'bracket' is called method
# just bracket is called function
# ctrl + / is used for commenting

arr2d.shape #attribute

#(3,3) 3 rows and 3 columns

(3, 3)

In [5]:
#it may sound stupid but this error is intended for learning purpose
arrp= np.array([[1,7],[2,3,4]])

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_6356\2721988659.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arrp= np.array([[1,7],[2,3,4]])


In [2]:
#day 3 

import numpy as np




In [6]:
#make sure to have same list size when putting inside an array
#make sure to open a parenthesis
#make sure to open double brackets not curly braces mind you

array= np.array([[1,7,9],[2,3,4]])

In [7]:
array.shape

(2, 3)

In [8]:
# array call

array

array([[1, 7, 9],
       [2, 3, 4]])

In [9]:
#calling first row
array[0]

array([1, 7, 9])

In [20]:
#calling second row



array[1]

array([2, 3, 4])

In [21]:
# calling first column
#rules to keep in  mind 
#first call the entire array/matrix
# m[first row(0): last row]
#to access columns m[firstrow: last row,column number]

array[0:2,0] # it goes upto  but not including 2 elements in the first bracket and calls first column with '0'

array([1, 2])

In [22]:
#calling second column

array[0:2,1] # it goes upto  but not including 2 elements in the first bracket and calls second column with '1' in the second bracket


array([7, 3])

In [25]:
# lets see the difference in matrix func

lis=[1,2,3],[4,5,6],[7,8,9]
matrix= np.matrix(lis)
matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
#calling first row
matrix[0]

matrix([[1, 2, 3]])

In [27]:
#calling first column

matrix[0:3,0]

matrix([[1],
        [4],
        [7]])

In [28]:
#calling third column

matrix[0:3,2]

matrix([[3],
        [6],
        [9]])

In [29]:
#calling all rows

matrix[0:3]

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
#call a particular element 
#call an element from row 0 and column 1
matrix[0,1]

2

In [31]:
array

array([[1, 7, 9],
       [2, 3, 4]])

In [32]:
array[0,1]

7

In [36]:
#boolean filtering
#use this method only with an array

arr=np.arange(0,11)

In [37]:
boolean_filter=arr>6

boolean_filter

array([False, False, False, False, False, False, False,  True,  True,
        True,  True])

In [38]:
#boolean filtered array
arr[boolean_filter]

array([ 7,  8,  9, 10])

In [39]:
#simple method to accomplish the same feat as above

arr[arr>6]

array([ 7,  8,  9, 10])

In [40]:
#it does not work with normal lists it works only with arrays
lis=list(range(0,11))

lis[lis>6]

TypeError: '>' not supported between instances of 'list' and 'int'

In [42]:
#another method to create array
arr=np.array(range(0,11))

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
greater_than_six=arr[arr>6]

In [52]:
counter=0
for i in greater_than_six:
    
    counter=counter+1
    
counter
    


4

In [54]:
# we don't have to use for loop it appears when we arrays take for instance

arr=np.array(range(0,11))

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr +5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
# you see that? we didn't for loop to add 5 to each element in the array. wonderful isn't?

#lets see if the original array was changed 

arr

#see the original array is not impacted unless we do something like this

arr= arr+5
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
#we can also use some amazing functions with array in numpy

#gets sin value of each element in the array

np.sin(arr)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [60]:

#gets log value of each element in the array
np.log(arr)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 ])

In [70]:
#inserting 0 in the 11th space in the existing array

arr=np.insert(arr,11,0)

In [71]:
np.log(arr)

#in normal python 1/0 gives zero error but in numpy 1/0 gives infinity with a runtime admonishment ofcourse

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_6356\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 ,       -inf])

In [72]:
# sum funtion

np.sum(arr)

110

In [73]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,  0])

In [74]:
#mean

np.mean(arr)

9.166666666666666

In [75]:
# variance

np.var(arr)

16.805555555555557

In [76]:
# standard deviation

np.std(arr)

4.099457958749615

In [77]:
# creating a multidimensional array

#arange = array+range

arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
arr=arr.reshape(5,5)

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
# performing sum on our 25 dimensional array

arr.sum()

300

In [83]:
# performing sum by individual rows
#axis =0 column wise sum
#axis =1 row wise sum

arr.sum(axis=0)

array([50, 55, 60, 65, 70])

In [84]:
arr.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [85]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [88]:
account_total=account_transactions.sum()

In [89]:
account_total

2720