# day 168

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as image
import seaborn as sns
from IPython.display import display,Math
import sympy as sym
sym.init_printing()

# 2. Create a random tensor with shape (7, 7).

In [ ]:
tensor_from_2 = torch.randint(1,9,(7,7))

tensor_from_2

tensor([[1, 3, 4, 6, 6, 4, 7],
        [5, 8, 2, 2, 7, 5, 4],
        [7, 2, 6, 7, 2, 5, 4],
        [3, 3, 8, 1, 5, 1, 8],
        [5, 2, 6, 8, 5, 6, 6],
        [4, 3, 7, 6, 5, 7, 1],
        [3, 3, 1, 1, 7, 6, 8]])

# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
another_tensor = torch.tensor(np.random.randn(1,7))

operation3 = np.matmul(tensor_from_2,another_tensor.T)
operation3

tensor([[-10.5956],
        [ -6.8321],
        [-15.8813],
        [ -7.6624],
        [-16.1908],
        [-19.1075],
        [ -1.6794]], dtype=torch.float64)

In [ ]:
np.dot(tensor_from_2,another_tensor.T)

array([[-10.59561975],
       [ -6.83209462],
       [-15.88131963],
       [ -7.6623727 ],
       [-16.19078472],
       [-19.10746313],
       [ -1.6793605 ]])

In [ ]:
torch.matmul(tensor_from_2,another_tensor.T)

'''this is the perfect example data type mismatch. we can fix it by changing the type of one or the other tensor.'''

RuntimeError: ignored

In [ ]:
torch.matmul(tensor_from_2.type(torch.float64),another_tensor.T.type(torch.float64))

tensor([[-10.5956],
        [ -6.8321],
        [-15.8813],
        [ -7.6624],
        [-16.1908],
        [-19.1075],
        [ -1.6794]], dtype=torch.float64)

# 4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [ ]:
# creating the tensor_from_2
torch.manual_seed(0)
tensor_from_2 = torch.randint(1,9,(7,7))

# creating the another_tensor
torch.manual_seed(0)
another_tensor = torch.tensor(np.random.randn(1,7))

# doing torch.matmul
torch.matmul(tensor_from_2.type(torch.float32),another_tensor.T.type(torch.float32))

tensor([[ 7.3892],
        [17.4966],
        [13.4106],
        [13.9460],
        [11.9201],
        [17.1266],
        [ 8.3624]])

# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [ ]:
# creating the tensor_from_2
torch.cuda.manual_seed(1234)
tensor_from_2 = torch.randint(1,9,(7,7))

# creating the another_tensor
torch.cuda.manual_seed(1234)
another_tensor = torch.tensor(np.random.randn(1,7))

# doing torch.matmul
torch.matmul(tensor_from_2.type(torch.float32),another_tensor.T.type(torch.float32))

tensor([[-13.2963],
        [ -4.6160],
        [-12.0944],
        [-16.6941],
        [-20.8933],
        [  6.0328],
        [  2.4800]])

# create reproducible results

In [ ]:
# creating the tensor_from_2
torch.manual_seed(1234)
tensor_from_2 = torch.randint(1,9,(7,7))

# creating the another_tensor
torch.manual_seed(1234)
another_tensor = torch.randn(1,7)

# doing torch.matmul
torch.matmul(tensor_from_2.type(torch.float32),another_tensor.T.type(torch.float32))

tensor([[-4.1140],
        [ 4.9254],
        [ 1.4087],
        [-1.0660],
        [-1.7453],
        [-2.4428],
        [-2.9928]])

# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [ ]:
# setting the device:
device = 'cuda' if torch.cuda.is_available() else 'cpu'


torch.manual_seed(1234)
# create the tensor1 and send it to gpu or cpu based on availability.
tensor1 = torch.randint(1,9,(2,3)).to(device)

# create the tensor2 and send it to gpu or cpu
torch.manual_seed(1234)
tensor2 = torch.rand(2,3).to(device)




# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors

In [ ]:
# it is reproducible.

output_of_7 = torch.matmul(tensor1.type(torch.float32),tensor2.T.type(torch.float32))
output_of_7

tensor([[3.6583, 8.0708],
        [3.4826, 5.9946]], device='cuda:0')

# 8. Find the maximum and minimum values of the output of 7.

In [ ]:
torch.max(output_of_7)

tensor(8.0708, device='cuda:0')

In [ ]:
torch.min(output_of_7)

tensor(3.4826, device='cuda:0')

# 9.Find the maximum and minimum index values of the output of 7.

In [ ]:
output_of_7

tensor([[3.6583, 8.0708],
        [3.4826, 5.9946]], device='cuda:0')

In [ ]:
print(torch.argmax(output_of_7))
'''it seems it flattens the whole matrix and counts in which index does the lowest value lie'''

tensor(1, device='cuda:0')

In [ ]:
print(torch.argmax(output_of_7,dim=1))

'''it sees which element in the matrix is the biggest row-wise'

tensor([1, 1], device='cuda:0')

In [ ]:
print(torch.argmax(output_of_7,dim=0))

'''it sees which elements in the matrix are biggest column-wise'''

tensor([0, 0], device='cuda:0')


'it sees which elements in the matrix are smallest column-wise'

In [ ]:
print(torch.argmin(output_of_7))

'''it flattens and counts'''

tensor(2, device='cuda:0')


'it flattens and counts'

In [ ]:
print(torch.argmin(output_of_7,dim=0))

''' colum-wise smalls'''

tensor([1, 1], device='cuda:0')


' colum-wise smalls'

In [ ]:
print(torch.argmin(output_of_7,dim=1))
'''row-wise smalls'''

tensor([0, 0], device='cuda:0')


'row-wise smalls'

# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
torch.manual_seed(7)
first_tensor = torch.rand(1,1,1,10)

torch.manual_seed(7)
second_tensor = torch.squeeze(first_tensor)



In [ ]:
first_tensor

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [ ]:
second_tensor

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

# day 171

# extra curriculam:

In [1]:
import torch
import numpy as np
import sympy as sym
from IPython.display import display,Math
sym.init_printing()
import matplotlib.pyplot as plt
import matplotlib.image as image

# playing with tensors

In [3]:
# converting a numpy array into a torch tensor.
np_array = np.array([[1,2],
                     [3,4]])

torch_tensor = torch.from_numpy(np_array)

torch_tensor




tensor([[1, 2],
        [3, 4]])

In [4]:
# type of the tensor is:
torch_tensor.type()

'torch.LongTensor'

In [5]:
# replacing the values of  the torch_tensor to become all 1's

all_ones = torch.ones_like(torch_tensor)

all_ones

tensor([[1, 1],
        [1, 1]])

In [6]:
# replacing the values of torch_tensor to bear random_values and its dtype is overidden.

random_numbers = torch.rand_like(torch_tensor,dtype=torch.float32)

random_numbers

tensor([[0.3946, 0.2030],
        [0.4902, 0.6630]])

In [9]:
# determing the shape of the output of a tensor

shape = (2,3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print('\n')
print(ones_tensor)
print('\n')
print(zeros_tensor)

tensor([[0.4427, 0.6883, 0.7701],
        [0.3537, 0.6800, 0.7774]])


tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# attributes of a tensor

tensor = torch.rand(2,3)

print(f'shape of the tensor is: {tensor.shape}')
print(f'dtype of the tensor is: {tensor.dtype}')
print(f'device the tensor is stored on: {tensor.device}')

shape of the tensor is: torch.Size([2, 3])
dtype of the tensor is: torch.float32
device the tensor is stored on: cpu


In [19]:
# accessing the last column of a tensor

tensor = torch.randn(4,3)
display(tensor)

print(f'last column of the tensor is: {tensor[:,-1]}')

tensor([[-0.1562,  0.8446, -1.2776],
        [ 1.2724,  0.5957,  0.6951],
        [ 1.4816,  0.7549, -2.1038],
        [ 0.6220, -0.0482, -2.4363]])

last column of the tensor is: tensor([-1.2776,  0.6951, -2.1038, -2.4363])


In [32]:
# stacking and concatenating the tensors

# concatenating
tensor1 = torch.randn(3,4)
print('it is tensor1: ')
display(tensor1)
print('\n')


tensor2 = torch.randn(3,4)
print('it is tensor2: ')
display(tensor2)
print('\n')


print('this is concatenated tensors at dim=0')
display(torch.cat([tensor1,tensor2],dim=0))
print('\n')


print('this is concatenated tensors in dim=1')
display(torch.cat([tensor1,tensor2],dim=1))
print('\n')

print('this is stacked tensors in dim=0')
display(torch.stack([tensor1,tensor2],dim=0))
print('\n')

print('this is stacked tensors in dim=1')
display(torch.stack([tensor1,tensor2],dim=1))
print('\n')

it is tensor1: 


tensor([[ 0.0998,  0.6903,  0.1774,  0.1925],
        [ 0.5877, -1.5478, -1.9110,  1.4226],
        [-0.8527, -1.4525, -0.9687, -0.1655]])



it is tensor2: 


tensor([[-0.0895, -0.4869,  0.0135, -1.2443],
        [ 0.0956, -0.2686, -0.1558, -0.4454],
        [-0.1447,  1.1772,  0.6181,  0.2192]])



this is concatenated tensors at dim=0


tensor([[ 0.0998,  0.6903,  0.1774,  0.1925],
        [ 0.5877, -1.5478, -1.9110,  1.4226],
        [-0.8527, -1.4525, -0.9687, -0.1655],
        [-0.0895, -0.4869,  0.0135, -1.2443],
        [ 0.0956, -0.2686, -0.1558, -0.4454],
        [-0.1447,  1.1772,  0.6181,  0.2192]])



this is concatenated tensors in dim=1


tensor([[ 0.0998,  0.6903,  0.1774,  0.1925, -0.0895, -0.4869,  0.0135, -1.2443],
        [ 0.5877, -1.5478, -1.9110,  1.4226,  0.0956, -0.2686, -0.1558, -0.4454],
        [-0.8527, -1.4525, -0.9687, -0.1655, -0.1447,  1.1772,  0.6181,  0.2192]])



this is stacked tensors in dim=0


tensor([[[ 0.0998,  0.6903,  0.1774,  0.1925],
         [ 0.5877, -1.5478, -1.9110,  1.4226],
         [-0.8527, -1.4525, -0.9687, -0.1655]],

        [[-0.0895, -0.4869,  0.0135, -1.2443],
         [ 0.0956, -0.2686, -0.1558, -0.4454],
         [-0.1447,  1.1772,  0.6181,  0.2192]]])



this is stacked tensors in dim=1


tensor([[[ 0.0998,  0.6903,  0.1774,  0.1925],
         [-0.0895, -0.4869,  0.0135, -1.2443]],

        [[ 0.5877, -1.5478, -1.9110,  1.4226],
         [ 0.0956, -0.2686, -0.1558, -0.4454]],

        [[-0.8527, -1.4525, -0.9687, -0.1655],
         [-0.1447,  1.1772,  0.6181,  0.2192]]])

In [38]:
# sum and item

tensor = torch.randint(1,9,(3,3))

print('this is the the tensor:')
display(tensor)
print('\n')

print('this is the sum of all elements in the tensor:')
display(tensor.sum())
print('\n')


print('lets see what the .item() method does:')
display(tensor.sum().item())
print('\n')

# item seems to fetch the item under concern from the tensor.

this is the the tensor:


tensor([[4, 6, 6],
        [4, 1, 6],
        [3, 7, 8]])



this is the sum of all elements in the tensor:


tensor(45)



lets see what the .item() method does:


45

# tensors to numpy array:



In [44]:
# converting a tensor to a numpy is a cake walk

torch_tensor = torch.randint(1,9,(3,3))
numpy_array = torch_tensor.numpy()

print('this is the numpy_array:')
display(numpy_array)
print('\n')

# converting from numpy_array back to a torch tensor
torch_tensor = torch.from_numpy(numpy_array)

print('this is the torch_tensor:')
display(torch_tensor)
print('\n')


this is the numpy_array:


array([[3, 3, 2],
       [6, 5, 2],
       [5, 7, 3]])



this is the torch_tensor:


tensor([[3, 3, 2],
        [6, 5, 2],
        [5, 7, 3]])

# why tensors are called the facts of the universe?

* because tensors are mathematical objects that can be used to represent the physical world's properties like no other mathematical representors, even matrix and vectors can only  store so much, tensors are above and beyond them.

* In her book, Infinity: Beyond the Beyond the Beyond, Lieber writes:"Tensors are the facts of the universe. They are the mathematical tools that we use to describe the relationships between physical quantities. They are the language of physics."

